/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetoindividuallilianep;

import java.awt.Color;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;



public class MonitoramentoLiliane extends javax.swing.JFrame {

   
    Random verificaCpu = new Random();
    Random verificaMemoria = new Random();
    Random verificaDisco = new Random();
    /**
     * Creates new form MonitoramentoLiliane
     */
    public MonitoramentoLiliane() {
        initComponents();
    }
    
    private void gerarNovosValores(){
        Double mostra1 = verificaCpu.nextDouble()* 100;
        lblMostraCpu.setText(String.format("%.1f", mostra1)+ "%");
        
          Double mostra2 = verificaDisco.nextDouble()* 100;
          lblMostraDisco.setText(String.format("%.1f", mostra2)+ "%");
        
          Double mostra3 = verificaMemoria.nextDouble()* 100;
          lblMostraRam.setText(String.format("%.1f", mostra3)+ "%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBG = new javax.swing.JPanel();
        jPanelCPU = new javax.swing.JPanel();
        lblCpu = new javax.swing.JLabel();
        lblImgCpu = new javax.swing.JLabel();
        lblMostraCpu = new javax.swing.JLabel();
        jPanelDisk = new javax.swing.JPanel();
        lblDisco = new javax.swing.JLabel();
        lblImgDisco = new javax.swing.JLabel();
        lblMostraDisco = new javax.swing.JLabel();
        jPanelRam = new javax.swing.JPanel();
        lblMemoria = new javax.swing.JLabel();
        lblImgRam = new javax.swing.JLabel();
        lblMostraRam = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblImgTitle = new javax.swing.JLabel();
        btnVerificarAut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelBG.setBackground(new java.awt.Color(204, 204, 255));
        jPanelBG.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBG.setForeground(new java.awt.Color(51, 51, 51));
        jPanelBG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelBG.setMaximumSize(new java.awt.Dimension(488, 535));
        jPanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCPU.setBackground(new java.awt.Color(0, 45, 92));
        jPanelCPU.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCPU.setToolTipText("");
        jPanelCPU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCpu.setBackground(new java.awt.Color(204, 255, 204));
        lblCpu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCpu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpu.setText("CPU : ");

        lblImgCpu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Victor\\Downloads\\cpu.png")); // NOI18N

        lblMostraCpu.setText("%");

        javax.swing.GroupLayout jPanelCPULayout = new javax.swing.GroupLayout(jPanelCPU);
        jPanelCPU.setLayout(jPanelCPULayout);
        jPanelCPULayout.setHorizontalGroup(
            jPanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCPULayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblImgCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostraCpu)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanelCPULayout.setVerticalGroup(
            jPanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCPULayout.createSequentialGroup()
                .addComponent(lblImgCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCPULayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMostraCpu))
                .addGap(34, 34, 34))
        );

        jPanelBG.add(jPanelCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 390, 100));

        jPanelDisk.setBackground(new java.awt.Color(31, 87, 118));
        jPanelDisk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDisk.setToolTipText("");

        lblDisco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDisco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisco.setText("DISCO : ");

        lblImgDisco.setIcon(new javax.swing.ImageIcon("C:\\Users\\Victor\\Downloads\\disco-rigido.png")); // NOI18N

        lblMostraDisco.setText("%");

        javax.swing.GroupLayout jPanelDiskLayout = new javax.swing.GroupLayout(jPanelDisk);
        jPanelDisk.setLayout(jPanelDiskLayout);
        jPanelDiskLayout.setHorizontalGroup(
            jPanelDiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiskLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblImgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostraDisco)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanelDiskLayout.setVerticalGroup(
            jPanelDiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiskLayout.createSequentialGroup()
                .addGroup(jPanelDiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDiskLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanelDiskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDisco)
                            .addComponent(lblMostraDisco))))
                .addGap(22, 22, 22))
        );

        jPanelBG.add(jPanelDisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 390, 100));

        jPanelRam.setBackground(new java.awt.Color(122, 166, 180));
        jPanelRam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelRam.setForeground(new java.awt.Color(0, 64, 94));

        lblMemoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMemoria.setText("Memória Ram:");

        lblImgRam.setIcon(new javax.swing.ImageIcon("C:\\Users\\Victor\\Downloads\\ram (4).png")); // NOI18N

        lblMostraRam.setText("%");

        javax.swing.GroupLayout jPanelRamLayout = new javax.swing.GroupLayout(jPanelRam);
        jPanelRam.setLayout(jPanelRamLayout);
        jPanelRamLayout.setHorizontalGroup(
            jPanelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgRam, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblMemoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMostraRam)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanelRamLayout.setVerticalGroup(
            jPanelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRamLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemoria)
                    .addComponent(lblMostraRam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelRamLayout.createSequentialGroup()
                .addComponent(lblImgRam, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanelBG.add(jPanelRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 390, 110));

        btnVerificar.setBackground(new java.awt.Color(20, 98, 91));
        btnVerificar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnVerificar.setForeground(new java.awt.Color(255, 255, 204));
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        jPanelBG.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 100, 30));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(19, 55, 72));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Monitoramento de SO");
        jPanelBG.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 363, -1));

        lblImgTitle.setIcon(new javax.swing.ImageIcon("C:\\Users\\Victor\\Downloads\\cms.png")); // NOI18N
        jPanelBG.add(lblImgTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 70));

        btnVerificarAut.setBackground(new java.awt.Color(20, 98, 91));
        btnVerificarAut.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnVerificarAut.setForeground(new java.awt.Color(255, 255, 204));
        btnVerificarAut.setText("Verificar Automático");
        btnVerificarAut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarAutActionPerformed(evt);
            }
        });
        jPanelBG.add(btnVerificarAut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        gerarNovosValores();
        
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnVerificarAutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarAutActionPerformed
       int delay = 2500;
       
       int intervalo = 2000;
       
    Timer tempo = new Timer();
    tempo.scheduleAtFixedRate(new TimerTask() {
           
           public void run() {
            gerarNovosValores();
           }
    }, delay,intervalo);
           
    }//GEN-LAST:event_btnVerificarAutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoLiliane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoLiliane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoLiliane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoLiliane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitoramentoLiliane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btnVerificarAut;
    private javax.swing.JPanel jPanelBG;
    private javax.swing.JPanel jPanelCPU;
    private javax.swing.JPanel jPanelDisk;
    private javax.swing.JPanel jPanelRam;
    private javax.swing.JLabel lblCpu;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblImgCpu;
    private javax.swing.JLabel lblImgDisco;
    private javax.swing.JLabel lblImgRam;
    private javax.swing.JLabel lblImgTitle;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel lblMostraCpu;
    private javax.swing.JLabel lblMostraDisco;
    private javax.swing.JLabel lblMostraRam;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
